BATCH_SIZE: 128
EPOCHS: 20
DEVICE: "cuda:0" # Replace with "cpu" if GPU is not available
LEARNING_RATE: 2e-5

DATASET_PATH:
  TRAINING_FILE: "data/Webpages_Classification_train_data.csv"
  TESTING_FILE: "data/Webpages_Classification_test_data.csv"

OUTPUTS:
  MODEL_OUTPUT: "output/models"
  ENCODERS: "output/encoders"
  SCALERS: "output/scalers"

ENCODERS_SCALERS:
  ECODER_OBJECTS : 
    who_is_encoder : who_is_encoder.pkl
    geo_loc_encoder : geo_loc_encoder.pkl
    https_encoder : https_encoder.pkl
    net_type_encoder : net_type_encoder.pkl
    tld_encoder : tld_encoder.pkl
  SCALER_OBJECTS :
    special_char_ss : special_char_ss.pkl
    content_len_ss : content_len_ss.pkl
