BATCH_SIZE: 128
EPOCHS: 20
DEVICE: "cuda:0" # Replace with "cpu" if GPU is not available
LEARNING_RATE: 2e-5

paths:
  base_path: "" # Add your current folder path
  TRAINING_FILE: "input/Webpages_Classification_train_data.csv"
  TESTING_FILE: "input/Webpages_Classification_test_data.csv"
  MODEL_OUTPUT: "models/"

encoders:
  who_is_en: "le_ss/who_is_encoder.pkl"
  geo_loc_en: "le_ss/geo_loc_encoder.pkl"
  https_en: "le_ss/https_encoder.pkl"
  net_type_en: "le_ss/net_type_encoder.pkl"
  tld_en: "le_ss/tld_encoder.pkl"

scalers:
  special_char_ss: "le_ss/special_char_ss.pkl"
  content_len_ss: "le_ss/content_len_ss.pkl"
